/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sketchengine.manatee;

public class AttrNotFound {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AttrNotFound(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AttrNotFound obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        manateeJNI.delete_AttrNotFound(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AttrNotFound(String name) {
    this(manateeJNI.new_AttrNotFound(name), true);
  }

  public String __str__() {
    return manateeJNI.AttrNotFound___str__(swigCPtr, this);
  }

}
