/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sketchengine.manatee;

public class Concordance {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Concordance(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Concordance obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        manateeJNI.delete_Concordance(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Concordance(Corpus corp, String filename) {
    this(manateeJNI.new_Concordance__SWIG_0(Corpus.getCPtr(corp), corp, filename), true);
  }

  public Concordance(Corpus corp, int fileno) {
    this(manateeJNI.new_Concordance__SWIG_1(Corpus.getCPtr(corp), corp, fileno), true);
  }

  public Concordance(Corpus corp, RangeStream rs, int inccoll) {
    this(manateeJNI.new_Concordance__SWIG_2(Corpus.getCPtr(corp), corp, RangeStream.getCPtr(rs), rs, inccoll), true);
  }

  public Concordance(Corpus corp, RangeStream rs) {
    this(manateeJNI.new_Concordance__SWIG_3(Corpus.getCPtr(corp), corp, RangeStream.getCPtr(rs), rs), true);
  }

  public Concordance(Concordance x) {
    this(manateeJNI.new_Concordance__SWIG_4(Concordance.getCPtr(x), x), true);
  }

  public void save(String filename, boolean save_linegroup, boolean partial, boolean append) {
    manateeJNI.Concordance_save__SWIG_0(swigCPtr, this, filename, save_linegroup, partial, append);
  }

  public void save(String filename, boolean save_linegroup, boolean partial) {
    manateeJNI.Concordance_save__SWIG_1(swigCPtr, this, filename, save_linegroup, partial);
  }

  public void save(String filename, boolean save_linegroup) {
    manateeJNI.Concordance_save__SWIG_2(swigCPtr, this, filename, save_linegroup);
  }

  public void save(String filename) {
    manateeJNI.Concordance_save__SWIG_3(swigCPtr, this, filename);
  }

  public void save(int fileno, boolean save_linegroup, boolean partial, boolean append) {
    manateeJNI.Concordance_save__SWIG_4(swigCPtr, this, fileno, save_linegroup, partial, append);
  }

  public void save(int fileno, boolean save_linegroup, boolean partial) {
    manateeJNI.Concordance_save__SWIG_5(swigCPtr, this, fileno, save_linegroup, partial);
  }

  public void save(int fileno, boolean save_linegroup) {
    manateeJNI.Concordance_save__SWIG_6(swigCPtr, this, fileno, save_linegroup);
  }

  public void save(int fileno) {
    manateeJNI.Concordance_save__SWIG_7(swigCPtr, this, fileno);
  }

  public int size() {
    return manateeJNI.Concordance_size(swigCPtr, this);
  }

  public int numofcolls() {
    return manateeJNI.Concordance_numofcolls(swigCPtr, this);
  }

  public int viewsize() {
    return manateeJNI.Concordance_viewsize(swigCPtr, this);
  }

  public int fullsize() {
    return manateeJNI.Concordance_fullsize(swigCPtr, this);
  }

  public boolean finished() {
    return manateeJNI.Concordance_finished(swigCPtr, this);
  }

  public void sync() {
    manateeJNI.Concordance_sync(swigCPtr, this);
  }

  public void set_collocation(int collnum, String cquery, String lctx, String rctx, int rank, boolean exclude_kwic) {
    manateeJNI.Concordance_set_collocation__SWIG_0(swigCPtr, this, collnum, cquery, lctx, rctx, rank, exclude_kwic);
  }

  public void set_collocation(int collnum, String cquery, String lctx, String rctx, int rank) {
    manateeJNI.Concordance_set_collocation__SWIG_1(swigCPtr, this, collnum, cquery, lctx, rctx, rank);
  }

  public void sort(String crit, boolean uniq) {
    manateeJNI.Concordance_sort__SWIG_0(swigCPtr, this, crit, uniq);
  }

  public void sort(String crit) {
    manateeJNI.Concordance_sort__SWIG_1(swigCPtr, this, crit);
  }

  public void relfreq_sort(String leftctx, String rightctx, String attr) {
    manateeJNI.Concordance_relfreq_sort(swigCPtr, this, leftctx, rightctx, attr);
  }

  public void set_sorted_view(IntVector sorted) {
    manateeJNI.Concordance_set_sorted_view(swigCPtr, this, IntVector.getCPtr(sorted), sorted);
  }

  public void reduce_lines(String crit) {
    manateeJNI.Concordance_reduce_lines(swigCPtr, this, crit);
  }

  public void delete_pnfilter(int collnum, boolean positive) {
    manateeJNI.Concordance_delete_pnfilter(swigCPtr, this, collnum, positive);
  }

  public void swap_kwic_coll(int collnum) {
    manateeJNI.Concordance_swap_kwic_coll(swigCPtr, this, collnum);
  }

  public void extend_kwic_coll(int collnum) {
    manateeJNI.Concordance_extend_kwic_coll(swigCPtr, this, collnum);
  }

  public void sort_idx(String crit, StrVector chars, IntVector idxs, boolean firstCharOnly) {
    manateeJNI.Concordance_sort_idx__SWIG_0(swigCPtr, this, crit, StrVector.getCPtr(chars), chars, IntVector.getCPtr(idxs), idxs, firstCharOnly);
  }

  public void sort_idx(String crit, StrVector chars, IntVector idxs) {
    manateeJNI.Concordance_sort_idx__SWIG_1(swigCPtr, this, crit, StrVector.getCPtr(chars), chars, IntVector.getCPtr(idxs), idxs);
  }

  public void distribution(IntVector vals, IntVector beginnings, int yrange) {
    manateeJNI.Concordance_distribution(swigCPtr, this, IntVector.getCPtr(vals), vals, IntVector.getCPtr(beginnings), beginnings, yrange);
  }

  public double compute_ARF() {
    return manateeJNI.Concordance_compute_ARF(swigCPtr, this);
  }

  public void set_linegroup(int linenum, int group) {
    manateeJNI.Concordance_set_linegroup(swigCPtr, this, linenum, group);
  }

  public void set_linegroup_globally(int group) {
    manateeJNI.Concordance_set_linegroup_globally(swigCPtr, this, group);
  }

  public int set_linegroup_at_pos(long pos, int group) {
    return manateeJNI.Concordance_set_linegroup_at_pos(swigCPtr, this, pos, group);
  }

  public void set_linegroup_from_conc(Concordance master) {
    manateeJNI.Concordance_set_linegroup_from_conc(swigCPtr, this, Concordance.getCPtr(master), master);
  }

  public int get_new_linegroup_id() {
    return manateeJNI.Concordance_get_new_linegroup_id(swigCPtr, this);
  }

  public void delete_linegroups(String grps, boolean invert) {
    manateeJNI.Concordance_delete_linegroups__SWIG_0(swigCPtr, this, grps, invert);
  }

  public void delete_linegroups(String grps) {
    manateeJNI.Concordance_delete_linegroups__SWIG_1(swigCPtr, this, grps);
  }

  public FastStream begs_FS() {
    long cPtr = manateeJNI.Concordance_begs_FS(swigCPtr, this);
    return (cPtr == 0) ? null : new FastStream(cPtr, true);
  }

  public RangeStream RS(boolean useview, int beg, int end) {
    long cPtr = manateeJNI.Concordance_RS__SWIG_0(swigCPtr, this, useview, beg, end);
    return (cPtr == 0) ? null : new RangeStream(cPtr, true);
  }

  public RangeStream RS(boolean useview, int beg) {
    long cPtr = manateeJNI.Concordance_RS__SWIG_1(swigCPtr, this, useview, beg);
    return (cPtr == 0) ? null : new RangeStream(cPtr, true);
  }

  public RangeStream RS(boolean useview) {
    long cPtr = manateeJNI.Concordance_RS__SWIG_2(swigCPtr, this, useview);
    return (cPtr == 0) ? null : new RangeStream(cPtr, true);
  }

  public RangeStream RS() {
    long cPtr = manateeJNI.Concordance_RS__SWIG_3(swigCPtr, this);
    return (cPtr == 0) ? null : new RangeStream(cPtr, true);
  }

  public void shuffle() {
    manateeJNI.Concordance_shuffle(swigCPtr, this);
  }

  public long beg_at(int idx) {
    return manateeJNI.Concordance_beg_at(swigCPtr, this, idx);
  }

  public long end_at(int idx) {
    return manateeJNI.Concordance_end_at(swigCPtr, this, idx);
  }

  public long coll_beg_at(int coll, int idx) {
    return manateeJNI.Concordance_coll_beg_at(swigCPtr, this, coll, idx);
  }

  public long coll_end_at(int coll, int idx) {
    return manateeJNI.Concordance_coll_end_at(swigCPtr, this, coll, idx);
  }

  public void switch_aligned(String corpname) {
    manateeJNI.Concordance_switch_aligned(swigCPtr, this, corpname);
  }

  public void get_aligned(StrVector aligned) {
    manateeJNI.Concordance_get_aligned(swigCPtr, this, StrVector.getCPtr(aligned), aligned);
  }

  public void add_aligned(String corpname) {
    manateeJNI.Concordance_add_aligned(swigCPtr, this, corpname);
  }

  public void delete_subparts() {
    manateeJNI.Concordance_delete_subparts(swigCPtr, this);
  }

  public void delete_struct_repeats(String struc) {
    manateeJNI.Concordance_delete_struct_repeats(swigCPtr, this, struc);
  }

  public Concordance(Corpus corp, String query, int sample_size, long full_size, int inccoll) {
    this(manateeJNI.new_Concordance__SWIG_5(Corpus.getCPtr(corp), corp, query, sample_size, full_size, inccoll), true);
  }

  public Concordance(Corpus corp, String query, int sample_size, long full_size) {
    this(manateeJNI.new_Concordance__SWIG_6(Corpus.getCPtr(corp), corp, query, sample_size, full_size), true);
  }

  public Concordance(Corpus corp, FastStream fs, int inccoll) {
    this(manateeJNI.new_Concordance__SWIG_7(Corpus.getCPtr(corp), corp, FastStream.getCPtr(fs), fs, inccoll), true);
  }

  public Concordance(Corpus corp, FastStream fs) {
    this(manateeJNI.new_Concordance__SWIG_8(Corpus.getCPtr(corp), corp, FastStream.getCPtr(fs), fs), true);
  }

  public void get_linegroup_stat(IntVector ids, IntVector freqs) {
    manateeJNI.Concordance_get_linegroup_stat(swigCPtr, this, IntVector.getCPtr(ids), ids, IntVector.getCPtr(freqs), freqs);
  }

  public void linegroup_sort(IntVector ids, StrVector strs) {
    manateeJNI.Concordance_linegroup_sort(swigCPtr, this, IntVector.getCPtr(ids), ids, StrVector.getCPtr(strs), strs);
  }

  public Corpus corp() {
    long cPtr = manateeJNI.Concordance_corp(swigCPtr, this);
    return (cPtr == 0) ? null : new Corpus(cPtr, false);
  }

}
