/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sketchengine.manatee;

public class CorpInfo {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected CorpInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CorpInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        manateeJNI.delete_CorpInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String dump(int indent) {
    return manateeJNI.CorpInfo_dump__SWIG_0(swigCPtr, this, indent);
  }

  public String dump() {
    return manateeJNI.CorpInfo_dump__SWIG_1(swigCPtr, this);
  }

  public CorpInfo add_attr(String path) {
    long cPtr = manateeJNI.CorpInfo_add_attr(swigCPtr, this, path);
    return (cPtr == 0) ? null : new CorpInfo(cPtr, false);
  }

  public CorpInfo add_struct(String path) {
    long cPtr = manateeJNI.CorpInfo_add_struct(swigCPtr, this, path);
    return (cPtr == 0) ? null : new CorpInfo(cPtr, false);
  }

  public void set_opt(String path, String val) {
    manateeJNI.CorpInfo_set_opt(swigCPtr, this, path, val);
  }

  public String find_opt(String path) {
    return manateeJNI.CorpInfo_find_opt(swigCPtr, this, path);
  }

  public CorpInfo() {
    this(manateeJNI.new_CorpInfo(), true);
  }

}
