/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sketchengine.manatee;

public class IDIterator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public IDIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IDIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        manateeJNI.delete_IDIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int next() {
    return manateeJNI.IDIterator_next(swigCPtr, this);
  }

  public int __getitem__(int array_index) {
    return manateeJNI.IDIterator___getitem__(swigCPtr, this, array_index);
  }

  public int __len__() {
    return manateeJNI.IDIterator___len__(swigCPtr, this);
  }

}
