/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sketchengine.manatee;

public class KWICLines {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected KWICLines(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KWICLines obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        manateeJNI.delete_KWICLines(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public KWICLines(Corpus corp, RangeStream r, String left, String right, String kwica, String ctxa, String struca, String refa, int maxctx) {
    this(manateeJNI.new_KWICLines__SWIG_0(Corpus.getCPtr(corp), corp, RangeStream.getCPtr(r), r, left, right, kwica, ctxa, struca, refa, maxctx), true);
  }

  public KWICLines(Corpus corp, RangeStream r, String left, String right, String kwica, String ctxa, String struca, String refa) {
    this(manateeJNI.new_KWICLines__SWIG_1(Corpus.getCPtr(corp), corp, RangeStream.getCPtr(r), r, left, right, kwica, ctxa, struca, refa), true);
  }

  public boolean nextcontext() {
    return manateeJNI.KWICLines_nextcontext(swigCPtr, this);
  }

  public boolean nextline() {
    return manateeJNI.KWICLines_nextline(swigCPtr, this);
  }

  public boolean skip(int count) {
    return manateeJNI.KWICLines_skip(swigCPtr, this, count);
  }

  public long get_pos() {
    return manateeJNI.KWICLines_get_pos(swigCPtr, this);
  }

  public int get_kwiclen() {
    return manateeJNI.KWICLines_get_kwiclen(swigCPtr, this);
  }

  public long get_ctxbeg() {
    return manateeJNI.KWICLines_get_ctxbeg(swigCPtr, this);
  }

  public long get_ctxend() {
    return manateeJNI.KWICLines_get_ctxend(swigCPtr, this);
  }

  public StrVector get_ref_list() {
    return new StrVector(manateeJNI.KWICLines_get_ref_list(swigCPtr, this), true);
  }

  public String get_refs() {
    return manateeJNI.KWICLines_get_refs(swigCPtr, this);
  }

  public StrVector get_left() {
    return new StrVector(manateeJNI.KWICLines_get_left(swigCPtr, this), true);
  }

  public StrVector get_kwic() {
    return new StrVector(manateeJNI.KWICLines_get_kwic(swigCPtr, this), true);
  }

  public StrVector get_right() {
    return new StrVector(manateeJNI.KWICLines_get_right(swigCPtr, this), true);
  }

  public int get_linegroup() {
    return manateeJNI.KWICLines_get_linegroup(swigCPtr, this);
  }

}
