/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sketchengine.manatee;

public class MLTStream {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected MLTStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MLTStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        manateeJNI.delete_MLTStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MLTStream.change_type_t change_type() {
    return MLTStream.change_type_t.swigToEnum(manateeJNI.MLTStream_change_type(swigCPtr, this));
  }

  public long change_size() {
    return manateeJNI.MLTStream_change_size(swigCPtr, this);
  }

  public long change_newsize() {
    return manateeJNI.MLTStream_change_newsize(swigCPtr, this);
  }

  public int concat_value(int attrn) {
    return manateeJNI.MLTStream_concat_value(swigCPtr, this, attrn);
  }

  public long orgpos() {
    return manateeJNI.MLTStream_orgpos(swigCPtr, this);
  }

  public long newpos() {
    return manateeJNI.MLTStream_newpos(swigCPtr, this);
  }

  public boolean end() {
    return manateeJNI.MLTStream_end(swigCPtr, this);
  }

  public long newfinal() {
    return manateeJNI.MLTStream_newfinal(swigCPtr, this);
  }

  public void next() {
    manateeJNI.MLTStream_next(swigCPtr, this);
  }

  public long find_org(long pos) {
    return manateeJNI.MLTStream_find_org(swigCPtr, this, pos);
  }

  public long find_new(long pos) {
    return manateeJNI.MLTStream_find_new(swigCPtr, this, pos);
  }

  public final static class change_type_t {
    public final static MLTStream.change_type_t KEEP = new MLTStream.change_type_t("KEEP", manateeJNI.MLTStream_KEEP_get());
    public final static MLTStream.change_type_t CONCAT = new MLTStream.change_type_t("CONCAT", manateeJNI.MLTStream_CONCAT_get());
    public final static MLTStream.change_type_t DELETE = new MLTStream.change_type_t("DELETE", manateeJNI.MLTStream_DELETE_get());
    public final static MLTStream.change_type_t INSERT = new MLTStream.change_type_t("INSERT", manateeJNI.MLTStream_INSERT_get());
    public final static MLTStream.change_type_t MORPH = new MLTStream.change_type_t("MORPH", manateeJNI.MLTStream_MORPH_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static change_type_t swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + change_type_t.class + " with value " + swigValue);
    }

    private change_type_t(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private change_type_t(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private change_type_t(String swigName, change_type_t swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static change_type_t[] swigValues = { KEEP, CONCAT, DELETE, INSERT, MORPH };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
