/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.sketchengine.manatee;

public class NumVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public NumVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(NumVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        manateeJNI.delete_NumVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public NumVector() {
    this(manateeJNI.new_NumVector__SWIG_0(), true);
  }

  public NumVector(long n) {
    this(manateeJNI.new_NumVector__SWIG_1(n), true);
  }

  public long size() {
    return manateeJNI.NumVector_size(swigCPtr, this);
  }

  public long capacity() {
    return manateeJNI.NumVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    manateeJNI.NumVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return manateeJNI.NumVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    manateeJNI.NumVector_clear(swigCPtr, this);
  }

  public void add(long x) {
    manateeJNI.NumVector_add(swigCPtr, this, x);
  }

  public long get(int i) {
    return manateeJNI.NumVector_get(swigCPtr, this, i);
  }

  public void set(int i, long val) {
    manateeJNI.NumVector_set(swigCPtr, this, i, val);
  }

}
