/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : regexopt.g
 *     -                            On : 2015-04-08 21:26:52
 *     -                 for the lexer : regexoptLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
regexoptLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef pregexoptLexer, which is returned from a call to regexoptLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in pregexoptLexer are  as follows:
 *
 *  - 
 void
      pregexoptLexer->ALNUM(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->ALPHA(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->BLANK(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->CNTRL(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->DIGIT(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->GRAPH(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->LOWER(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->PRINT(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->PUNCT(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->SPACE(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->UPPER(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->XDIGIT(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->WS_(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->LPAREN(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->RPAREN(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->LBRACKET(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->RBRACKET(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->LBRACE(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->RBRACE(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->BINOR(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->STAR(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->PLUS(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->QUEST(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->DOT(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->ZEROANDMORE(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->ONEANDMORE(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->TWOANDMORE(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->ESC(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->BACKREF(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->SPECIAL(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->NOMETA(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->ENUM(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->CHARCLASS(pregexoptLexer)
 *  - 
 void
      pregexoptLexer->Tokens(pregexoptLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_regexoptLexer_H
#define _regexoptLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

    #include "cqpeval.hh"
    #define _empty NULL



// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct regexoptLexer_Ctx_struct regexoptLexer, * pregexoptLexer;



    // Copyright (c) 2014-2015 Milos Jakubicek


#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
regexoptLexer

 */
struct regexoptLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mALNUM)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mALPHA)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mBLANK)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mCNTRL)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mDIGIT)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mGRAPH)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mLOWER)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mPRINT)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mPUNCT)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mSPACE)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mUPPER)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mXDIGIT)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mWS_)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mLPAREN)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mRPAREN)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mLBRACKET)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mRBRACKET)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mLBRACE)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mRBRACE)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mBINOR)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mSTAR)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mPLUS)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mQUEST)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mDOT)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mZEROANDMORE)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mONEANDMORE)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mTWOANDMORE)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mESC)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mBACKREF)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mSPECIAL)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mNOMETA)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mENUM)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mCHARCLASS)	(struct regexoptLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct regexoptLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct regexoptLexer_Ctx_struct * ctx);
    void	    (*free)   (struct regexoptLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API pregexoptLexer regexoptLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API pregexoptLexer regexoptLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define ALNUM      4
#define ALPHA      5
#define AND      6
#define BACKREF      7
#define BINOR      8
#define BLANK      9
#define CHARCLASS      10
#define CNTRL      11
#define DIGIT      12
#define DOT      13
#define ENUM      14
#define ESC      15
#define GRAPH      16
#define LBRACE      17
#define LBRACKET      18
#define LOWER      19
#define LPAREN      20
#define NOMETA      21
#define ONE      22
#define ONEANDMORE      23
#define PLUS      24
#define PRINT      25
#define PUNCT      26
#define QUEST      27
#define RBRACE      28
#define RBRACKET      29
#define RPAREN      30
#define SEPARATOR      31
#define SPACE      32
#define SPECIAL      33
#define STAR      34
#define TWOANDMORE      35
#define UPPER      36
#define WS_      37
#define XDIGIT      38
#define ZEROANDMORE      39
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for regexoptLexer
 * =============================================================================
 */
/** } */


#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
