#!/usr/bin/env python

import manatee

def print_region(region):
    for i in range(0, len(region), 2):
        print "%s" % region[i],

def print_result(posBegin, posEnd, refattr, corp, attrs, structs, lrCtxSize,
                 attrdelim, posdelim, kwicdelim):
    if refattr:
        ref = corp.get_attr (refattr)
        print '#%i,%s' % (posBegin, ref.pos2str (posBegin)),
    else:
        print '#%i' % posBegin,

    corpRegion = manatee.CorpRegion(corp, attrs, structs)
    leftCtx = corpRegion.region(posBegin - lrCtxSize[0], posBegin, posdelim,
                                attrdelim)
    kwic = corpRegion.region(posBegin, posEnd, posdelim, attrdelim)
    rightCtx = corpRegion.region(posEnd, posEnd + lrCtxSize[1], posdelim,
                                 attrdelim)

    kwicbeg, kwicend = kwicdelim.split(",")
    print_region(leftCtx)
    print kwicbeg,
    print_region(kwic)
    print kwicend,
    print_region(rightCtx)
    print

def corp_query (corpname, query, refattr, ctxSize, hardcut, attrs, structs,
                defattr, gdex_conf, attrdelim, posdelim, kwicdelim):

    if attrdelim[0] == "\\":
        attrdelim = attrdelim.decode("string_escape")
    if posdelim[0] == "\\":
        posdelim = posdelim.decode("string_escape")
    try:
        ctxSize = int(ctxSize)
        lrCtxSize = (ctxSize, ctxSize)
    except:
        lrCtxSize = map(int, ctxSize.split(","))

    corp = manatee.Corpus (corpname)
    corp.set_default_attr(defattr)
    result = corp.eval_query (query)
    if gdex_conf:
        try:
            import gdex
        except:
            import gdex_old as gdex
        result.thisown = False
        conc = manatee.Concordance (corp, result)
        if gdex_conf == "-":
            gdex_conf = None
        try:
            G = gdex.GDEX (corp, gdex_conf)
        except:
            G = gdex.GDEX (corp) # old GDEX
        G.entryConc (conc) # load input
        if hardcut == -1:
            hardcut = 100
        G_sort = G.best_k (hardcut, hardcut) # compute and return sorted list
        for _, concnum in G_sort:
            print_result(conc.beg_at(concnum), conc.end_at(concnum), refattr,
                         corp, attrs, structs, lrCtxSize, attrdelim, posdelim,
                         kwicdelim)
    else:
        while (hardcut > 0 or hardcut == -1) and not result.end():
            print_result(result.peek_beg(), result.peek_end(), refattr, corp,
                         attrs, structs, lrCtxSize, attrdelim, posdelim,
                         kwicdelim)
            result.next()
            if hardcut != -1:
                hardcut -= 1


if __name__ == '__main__':
    from sys import argv, path
    from distutils.sysconfig import get_python_lib;
    args = {"-r" : None, "-c" : 15, "-h" : -1, "-a" : "word,lemma,tag",
            "-s" : "s,p,doc", "-d": "word", "-g" : None, 
            "-m" : get_python_lib() + "/bonito2/", "-e": "/", "-l": " ",
            "-k" : "<,>"}
    if argv[2:]:
        import getopt
        opts, _ = getopt.getopt(argv[3:], "r:c:h:a:s:d:g:m:e:l:k:")
        args.update(dict(opts))
        if args["-k"].count(",") > 1:
            raise Exception("KWIC delimiter must not contain a comma")
        path.insert(0, args["-m"])
        corp_query(argv[1], argv[2], args["-r"], args["-c"], int(args["-h"]),
                   args["-a"], args["-s"], args["-d"], args["-g"], args["-e"],
                   args["-l"], args["-k"])
    else:
        print '''Usage: corpquery.py CORPUSNAME QUERY [ OPTIONS ]\n
Options:\n
  -r ATTR               reference attribute
                        (default: %s)
  -c LEFT,RIGHT | BOTH  left and right or both context length
                        (default: %d)
  -h LIMIT              maximum number of results
                        (default: %d)
  -a ATTR1,ATTR2,...    comma separated list of attributes to be shown
                        default: %s)
  -s STR1,STR2...       comma separated list of structures to be shown
                        (use struct.attr or struct.* to show structure attributes;
                        default: %s)
  -d DEFAULT_ATTR       default positional attribute
                        (default: %s)
  -g GDEX_CONF          use GDEX with a given GDEX_CONF configuration file
                        (default: %s; use - for default configuration)
                        use -h to set the result size (default: 100)
  -m GDEX_MODULE_DIR    GDEX module path (directory with gdex.py or gdex_old.py)
                        (default: %s)
  -e DELIMITER          positional attribute delimiter (default: %s)
  -l DELIMITER          positions delimiter (default: %s)
  -k BEGIN,END          mark beginning/end of KWIC by BEGIN/END (default: %s)
''' % (args["-r"], args["-c"], args["-h"], args["-a"], args["-s"], args["-d"], args["-g"],
        args["-m"], args["-e"], args["-l"], args["-k"])

# vim: ts=4 sw=4 sta et sts=4 si tw=80:
